PatronesDisenoASP/Models/ErrorViewModel.cs
namespace PatronesDisenoASP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PatronesDisenoASP/Models/ViewModels/BeerViewModel.cs
namespace PatronesDisenoASP.Models.ViewModels
{
    public class BeerViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Style { get; set; }
    }
}

PatronesDisenoASP/Models/ViewModels/FormBeerViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PatronesDisenoASP.Models.ViewModels
{
    public class FormBeerViewModel
    {
        [Required]
        [Display(Name = "Nombre")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Estilo")]
        public string Style { get; set; }
        [Display(Name = "Marca")]
        public Guid? BrandId { get; set; }
        [Display(Name = "Otra marca")]
        public string OtherBrand { get; set; }
    }
}

PatronesDisenoASP/Controllers/BeerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Patrones.Modelos.Data;
using Patrones.Repositorio;
using PatronesDisenoASP.Models.ViewModels;
using PatronesDisenoASP.Strategies;

namespace PatronesDisenoASP.Controllers
{
    public class BeerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public BeerController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            IEnumerable<BeerViewModel> cervezas = from d in _unitOfWork.Beers.Get()
                                                  select new BeerViewModel
                                                  {
                                                      Id = d.BeerId,
                                                      Name = d.Name,
                                                      Style = d.Style,
                                                  };

            return View("Index", cervezas);
        }

        [HttpGet]
        public IActionResult Add()
        {

            GetBrandsData();
            return View();
        }

        [HttpPost]
        public IActionResult Add(FormBeerViewModel beerVM)
        {
            if(!ModelState.IsValid)
            {
                GetBrandsData();
                return View("Add",beerVM);
            }

            var context = beerVM.BrandId == null ?
                          new BeerContext(new BeerWithBrandStrategy()) :
                          new BeerContext(new BeerStrategy());

            context.Add(beerVM, _unitOfWork);

            return RedirectToAction("Index");
        }


        #region Helpers
        private void GetBrandsData()
        {
            var brands = _unitOfWork.Brands.Get();
            ViewBag.Brands = new SelectList(brands, "BrandId", "Name");
        }
        #endregion
    }
}

PatronesDisenoASP/Controllers/HomeController.cs
using Herramientas;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Patrones.Modelos.Data;
using PatronesDiseno.Repositorio;
using PatronesDisenoASP.Configuration;
using PatronesDisenoASP.Models;
using System.Diagnostics;

namespace PatronesDisenoASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly IOptions<MyConfig> _config;
        private readonly IRepository<Beer> _beerRepository;
        public HomeController(IOptions<MyConfig> config, IRepository<Beer> repository)
        {
            _config = config;
            _beerRepository = repository;
        }

        public IActionResult Index()
        {
            Log.GetInstance(_config.Value.PathLog).Save("Entro a Index");

            IEnumerable<Beer> lst = _beerRepository.Get();


            return View("Index", lst);
        }

        public IActionResult Privacy()
        {
            Log.GetInstance(_config.Value.PathLog).Save("Entro a Privacy");
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PatronesDisenoASP/Controllers/ProductDetailController.cs
using Herramientas.Earns;
using Microsoft.AspNetCore.Mvc;

namespace PatronesDisenoASP.Controllers
{
    public class ProductDetailController : Controller
    {
        private EarnFactory _localEarnFactory;

        public ProductDetailController(LocalEarnFactory localEarnFactory)
        {
            _localEarnFactory = localEarnFactory;
        }

        public IActionResult Index(decimal total)
        {
            //factories
         
            FoereignEarnFactory FEFactory = new FoereignEarnFactory(0.60m, 20);

            var localEarn = _localEarnFactory.GetEarns();
            var feEarn = FEFactory.GetEarns();

            ViewBag.totalLocal = total + localEarn.Earn(total);
            ViewBag.totalForeign = total + feEarn.Earn(total);
            

            return View();
        }
    }
}

PatronesDisenoASP/Views/Beer/Add.cshtml
@model DesignPatternsAsp.Models.ViewModels.FormBeerViewModel

<form asp-controller="Beer" asp-action="Add" method="post">

    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Style"></label>
        <input class="form-control" asp-for="Style" />
        <span asp-validation-for="Style" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="BrandId"></label>
        <select class="form-control" asp-for="BrandId" asp-items="@ViewBag.Brands">
            <option value="">--- Selecciona marca ---</option>
        </select>
        <span asp-validation-for="BrandId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="OtherBrand"></label>
        <input class="form-control" asp-for="OtherBrand" />
        <span asp-validation-for="OtherBrand" class="text-danger"></span>
    </div>

    <div class="form-group">
        <button class="btn btn-primary" type="submit">Guardar</button>
    </div>
</form>

PatronesDisenoASP/Views/Beer/Index.cshtml
@using PatronesDisenoASP.Models.ViewModels
@model IEnumerable<BeerViewModel>


<div class="row">
    <div class="col-12 ">
        <a class="btn btn-primary" href="~/Beer/Add">Nueva cerveza</a>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table class="table">
            <tr>
                <th>Nombre</th>
            </tr>
            @foreach (var beer in Model)
            {
                <tr>
                    <td>@beer.Name</td>
                </tr>
            }
        </table>
    </div>
</div>

PatronesDisenoASP/Views/Home/Index.cshtml
@using Patrones.Modelos.Data
@model IEnumerable<Beer>


<div class="row">
    <div class="col-12">
        @foreach (var beer in Model)
        {
            <p>@beer.Name</p>
        }
    </div>
</div>

PatronesDisenoASP/Views/ProductDetail/Index.cshtml
@{
    decimal totalLocal = (decimal)ViewBag.totalLocal;
    decimal totalF = (decimal)ViewBag.totalForeign;
}

<div class="row">

    <div class="col-12">
        <label>Total Local</label>
        <b>@totalLocal</b>
    </div>
    <div class="col-12">
        <label>Total Local</label>
        <b>@totalF</b>
    </div>

</div>

PatronesDisenoASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PatronesDisenoASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PatronesDisenoASP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PatronesDisenoASP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PatronesDisenoASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>